apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: us.icr.io/2_IntroKubernetes/hello-world:1
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: icr
